# Generated by Django 3.2.4 on 2021-06-22 11:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Usell', 'Usell'), ('Belinee', 'Belinee'), ('MobiUz', 'MobiUz'), ('Uzmobile', 'Uzmobile')], max_length=20)),
                ('image', models.ImageField(upload_to='company/')),
            ],
        ),
        migrations.CreateModel(
            name='Daqiqalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Foydali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Xizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='X_Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('haqida', ckeditor.fields.RichTextField()),
                ('xizmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.xizmatlar')),
            ],
        ),
        migrations.CreateModel(
            name='Tariflar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.tariflar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='T_Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('muddati', models.IntegerField()),
                ('narxi', models.FloatField()),
                ('haqida', ckeditor.fields.RichTextField()),
                ('tariflar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tariflar')),
            ],
        ),
        migrations.CreateModel(
            name='SMS_Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('muddati', models.IntegerField()),
                ('narxi', models.FloatField()),
                ('haqida', ckeditor.fields.RichTextField()),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sms')),
            ],
        ),
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.internet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='I_Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('hajmi', models.IntegerField()),
                ('narxi', models.FloatField()),
                ('haqida', ckeditor.fields.RichTextField()),
                ('internet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.internet')),
            ],
        ),
        migrations.CreateModel(
            name='F_Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('haqida', ckeditor.fields.RichTextField()),
                ('foydali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foydali')),
            ],
        ),
        migrations.CreateModel(
            name='D_Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('muddati', models.IntegerField()),
                ('narxi', models.FloatField()),
                ('haqida', ckeditor.fields.RichTextField()),
                ('daqiqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.daqiqalar')),
            ],
        ),
    ]
