# Generated by Django 3.2.4 on 2021-06-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210622_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(choices=[('ucell', 'Ucell'), ('beeline', 'Beeline'), ('mobiuz', 'MobiUz'), ('uzmobile', 'UzMobile')], max_length=20),
        ),
    ]
