# Generated by Django 3.2.4 on 2021-06-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_company_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Kompaniya'},
        ),
        migrations.AlterModelOptions(
            name='d_paket',
            options={'verbose_name_plural': 'Daqiqalar'},
        ),
        migrations.AlterModelOptions(
            name='daqiqalar',
            options={'verbose_name_plural': 'Daqiqa'},
        ),
        migrations.AlterModelOptions(
            name='f_paket',
            options={'verbose_name_plural': 'Foyda'},
        ),
        migrations.AlterModelOptions(
            name='foydali',
            options={'verbose_name_plural': 'Foyda'},
        ),
        migrations.AlterModelOptions(
            name='i_paket',
            options={'verbose_name_plural': 'Internetlar'},
        ),
        migrations.AlterModelOptions(
            name='internet',
            options={'verbose_name_plural': 'Internet'},
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name_plural': 'SMS'},
        ),
        migrations.AlterModelOptions(
            name='sms_paket',
            options={'verbose_name_plural': 'SMSlar'},
        ),
        migrations.AlterModelOptions(
            name='t_paket',
            options={'verbose_name_plural': 'Tariflar'},
        ),
        migrations.AlterModelOptions(
            name='tariflar',
            options={'verbose_name_plural': 'Tarif'},
        ),
        migrations.AlterModelOptions(
            name='x_paket',
            options={'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='xizmatlar',
            options={'verbose_name_plural': 'Xizmat'},
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(choices=[('Ucell', 'ucell'), ('Beeline', 'beeline'), ('MobiUz', 'mobiuz'), ('Uzmobile', 'uzmobile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='internet',
            name='title',
            field=models.CharField(max_length=56),
        ),
    ]
